In [33]:
import numpy as np

a3x5 = np.arange(15).reshape(3, 5)
a3x5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
np.arange(6, 2)

array([], dtype=int64)

In [27]:
x_with_1 = np.append(np.ones(x.shape[0]), x)

In [28]:
x_with_1

array([ 1.,  1.,  1.,  1.,  3.,  5.])

In [15]:
import numpy as np
import random

# m denotes the number of examples here, not the number of features
def gradientDescent(x, y, theta, alpha, m, numIterations):
    xTrans = x.transpose()
    for i in range(0, numIterations):
        hypothesis = np.dot(x, theta)
        loss = hypothesis - y
        # avg cost per example (the 2 in 2*m doesn't really matter here.
        # But to be consistent with the gradient, I include it)
        cost = np.sum(loss ** 2) / (2 * m)
        print("Iteration %d | Cost: %f" % (i, cost))
        # avg gradient per example
        gradient = np.dot(xTrans, loss) / m
        # update
        theta = theta - alpha * gradient
    return theta


def genData(numPoints, bias, variance):
    x = np.zeros(shape=(numPoints, 2))
    y = np.zeros(shape=numPoints)
    # basically a straight line
    for i in range(0, numPoints):
        # bias feature
        x[i][0] = 1
        x[i][1] = i
        # our target variable
        y[i] = (i + bias) + random.uniform(0, 1) * variance
    return x, y

# gen 100 points with a bias of 25 and 10 variance as a bit of noise
x, y = genData(5, 25, 10)
m, n = np.shape(x)
numIterations= 100000
alpha = 0.0005
theta = np.ones(n)

In [16]:
x

array([[ 1.,  0.],
       [ 1.,  1.],
       [ 1.,  2.],
       [ 1.,  3.],
       [ 1.,  4.]])

In [17]:
theta

array([ 1.,  1.])

In [12]:
a

array([[ 0.11061421],
       [ 0.55062803],
       [ 0.08464685],
       [ 0.10600685],
       [ 0.19190898],
       [ 0.58989716],
       [ 0.83134959],
       [ 0.04916821],
       [ 0.66888246],
       [ 0.55072776]])